server:
  port: 8082

camel:
  component:
    kafka:
      brokers: localhost:9092



spring:
  datasource:
    password: admin
    username: postgres
    url:
      jdbc: postgresql://localhost:5433/wbcontent
  hibernate:
    ddl-auto=create-drop
    show-sql=true
    dialect=org.hibernate.dialect.PostgreSQLDialect
